name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build AlgebraicAutomata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Lean
        uses: leanprover/lean-action@v1

      - name: Fetch Mathlib cache
        run: lake exe cache get

      - name: Build Library
        run: lake build
